// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0QtKzSbAGke-ADalt4sTr9TvPExOi6N8',
    appId: '1:178148387712:web:b301f09d172086dc3def65',
    messagingSenderId: '178148387712',
    projectId: 'gogoos-app',
    authDomain: 'gogoos-app.firebaseapp.com',
    databaseURL:
        'https://gogoos-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gogoos-app.appspot.com',
    measurementId: 'G-LDPC8GMSJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi4TEBs-627uSS2X4dlhjVTjOsdQhPE8c',
    appId: '1:178148387712:android:b1e644f0e70a719f3def65',
    messagingSenderId: '178148387712',
    projectId: 'gogoos-app',
    databaseURL:
        'https://gogoos-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gogoos-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO1fWuW_4ngoKOWXrmci4r7HS0rYHZACI',
    appId: '1:178148387712:ios:a1c7f889e0313e5b3def65',
    messagingSenderId: '178148387712',
    projectId: 'gogoos-app',
    databaseURL:
        'https://gogoos-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gogoos-app.appspot.com',
    iosClientId:
        '178148387712-sk275b46kkj8mdkbjfpn2j87sj5hbjse.apps.googleusercontent.com',
    iosBundleId: 'com.example.gogoosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO1fWuW_4ngoKOWXrmci4r7HS0rYHZACI',
    appId: '1:178148387712:ios:b0d526d9f1380d423def65',
    messagingSenderId: '178148387712',
    projectId: 'gogoos-app',
    databaseURL:
        'https://gogoos-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gogoos-app.appspot.com',
    iosClientId:
        '178148387712-oelrh4jt64nes8ut0sk63bnhl8dhl2hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gogoosApp.RunnerTests',
  );
}
